package org.eclipse.imp.formatting.parser;

public interface FormattingSpecificationKWLexersym {
    public final static int
      Char_DollarSign = 20,
      Char__ = 21,
      Char_a = 3,
      Char_b = 12,
      Char_c = 22,
      Char_d = 23,
      Char_e = 2,
      Char_f = 13,
      Char_g = 6,
      Char_h = 24,
      Char_i = 25,
      Char_j = 26,
      Char_k = 27,
      Char_l = 4,
      Char_m = 7,
      Char_n = 14,
      Char_o = 8,
      Char_p = 15,
      Char_q = 28,
      Char_r = 5,
      Char_s = 16,
      Char_t = 9,
      Char_u = 10,
      Char_v = 29,
      Char_w = 30,
      Char_x = 11,
      Char_y = 31,
      Char_z = 32,
      Char_< = 17,
      Char_> = 1,
      Char_/ = 18,
      Char_EOF = 19;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 ">",
                 "e",
                 "a",
                 "l",
                 "r",
                 "g",
                 "m",
                 "o",
                 "t",
                 "u",
                 "x",
                 "b",
                 "f",
                 "n",
                 "p",
                 "s",
                 "<",
                 "/",
                 "EOF",
                 "DollarSign",
                 "_",
                 "c",
                 "d",
                 "h",
                 "i",
                 "j",
                 "k",
                 "q",
                 "v",
                 "w",
                 "y",
                 "z"
             };

    public final static boolean isValidForParser = true;
}
