
Options in effect for /home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:

    ACTION-BLOCK=("/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.java","/.","./")

    AST-DIRECTORY="./Ast"  AST-TYPE="Ast"  NOATTRIBUTES  NOAUTOMATIC-AST  
    NOBACKTRACK  BYTE  CONFLICTS  
    DAT-DIRECTORY="/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/"
    NOBACKTRACK  BYTE  CONFLICTS  
    DAT-FILE="/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexerdcl.data"
    NOBACKTRACK  BYTE  CONFLICTS  
    DCL-FILE="/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexerdcl.java"
    NOBACKTRACK  BYTE  CONFLICTS  NODEBUG  
    DEF-FILE="/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexerdef.java"
    NOBACKTRACK  BYTE  CONFLICTS  NODEBUG  NOEDIT  NOERROR-MAPS  ESCAPE='$'  
    EXPORT-TERMINALS=("/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationParsersym.java","TK_","")
    NOBACKTRACK  BYTE  CONFLICTS  NODEBUG  NOEDIT  NOERROR-MAPS  ESCAPE='$'  
    EXTENDS-PARSETABLE  FACTORY="new "  
    FILE-PREFIX="FormattingSpecificationLexer"  
    FILTER="FormattingSpecificationKWLexer.gi"  NOFIRST  NOFOLLOW  NOGLR  
    NOGOTO-DEFAULT  
    GRM-FILE="/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi"
    NOGOTO-DEFAULT  
    IMP-FILE="/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexerimp.java"
    NOGOTO-DEFAULT  
    INCLUDE-DIRECTORY="/home/jurgenv/imp/lpg.runtime.java/templates;/home/jurgenv/imp/org.eclipse.imp.lpg.metatooling/templates"
    NOGOTO-DEFAULT  LALR=1  LEGACY  NOLIST  MARGIN=4  MAX-CASES=1024  
    NAMES=OPTIMIZED  NONT-CHECK  OR_MARKER='|'  
    OUT-DIRECTORY="/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/"
    NAMES=OPTIMIZED  NONT-CHECK  OR_MARKER='|'  
    PACKAGE="org.eclipse.imp.formatting.parser"  NOPARENT-SAVE  
    PARSETABLE-INTERFACES="lpg.runtime.ParseTable"  PREFIX="Char_"  PRIORITY  
    PROGRAMMING_LANGUAGE=JAVA  
    PRS-FILE="/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexerprs.java"
    PROGRAMMING_LANGUAGE=JAVA  NOQUIET  READ-REDUCE  REMAP-TERMINALS  NOSCOPES
    NOSERIALIZE  NOSHIFT-DEFAULT  NOSINGLE-PRODUCTIONS  NOSOFT-KEYWORDS  
    NOSTATES  SUFFIX=""  
    SYM-FILE="/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexersym.java"
    NOSTATES  SUFFIX=""  TAB-FILE="FormattingSpecificationLexer.t"  TABLE  
    TEMPLATE="LexerTemplate.gi"  TRACE=CONFLICTS  NOVARIABLES  NOVERBOSE  
    NOVISITOR  VISITOR-TYPE="Visitor"  WARNINGS  NOXREF  

/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:102:31:102:38:2461:2468: Warning: The macro "$_NUMBER" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:107:31:107:45:2586:2600: Warning: The macro "$_DoubleLiteral" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:117:33:117:53:2819:2839: Warning: The macro "$_SINGLE_LINE_COMMENT" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:122:31:122:41:2947:2957: Warning: The macro "$_SEMICOLON" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:128:31:128:37:3067:3073: Warning: The macro "$_COMMA" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:134:31:134:36:3183:3188: Warning: The macro "$_PLUS" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:140:31:140:37:3298:3304: Warning: The macro "$_MINUS" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:146:31:146:38:3414:3421: Warning: The macro "$_ASSIGN" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:152:31:152:41:3531:3541: Warning: The macro "$_LEFTPAREN" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:158:31:158:42:3651:3662: Warning: The macro "$_RIGHTPAREN" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:164:31:164:41:3772:3782: Warning: The macro "$_LEFTBRACE" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:170:31:170:42:3892:3903: Warning: The macro "$_RIGHTBRACE" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:176:31:176:37:4013:4019: Warning: The macro "$_TIMES" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:182:31:182:38:4129:4136: Warning: The macro "$_DIVIDE" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:188:31:188:39:4246:4254: Warning: The macro "$_GREATER" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:194:31:194:36:4364:4369: Warning: The macro "$_LESS" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:200:31:200:37:4483:4489: Warning: The macro "$_EQUAL" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:206:31:206:40:4603:4612: Warning: The macro "$_NOTEQUAL" is undefined. No substitution made
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:34:9:34:11:824:826: Warning: The exported terminal symbol any was not generated by any rule in this grammar
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationKWLexer.gi:15:5:15:19:283:297: Warning: The exported terminal symbol begin_formatter was not generated by any rule in this grammar
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationKWLexer.gi:16:5:16:17:304:316: Warning: The exported terminal symbol end_formatter was not generated by any rule in this grammar
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationKWLexer.gi:17:5:17:18:323:336: Warning: The exported terminal symbol begin_language was not generated by any rule in this grammar
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationKWLexer.gi:18:5:18:16:343:354: Warning: The exported terminal symbol end_language was not generated by any rule in this grammar
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationKWLexer.gi:19:5:19:15:361:371: Warning: The exported terminal symbol begin_rules was not generated by any rule in this grammar
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationKWLexer.gi:20:5:20:13:378:386: Warning: The exported terminal symbol end_rules was not generated by any rule in this grammar
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationKWLexer.gi:21:5:21:14:393:402: Warning: The exported terminal symbol begin_rule was not generated by any rule in this grammar
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationKWLexer.gi:22:5:22:12:409:416: Warning: The exported terminal symbol end_rule was not generated by any rule in this grammar
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationKWLexer.gi:23:5:23:13:423:431: Warning: The exported terminal symbol begin_box was not generated by any rule in this grammar
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationKWLexer.gi:24:5:24:11:438:444: Warning: The exported terminal symbol end_box was not generated by any rule in this grammar
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationKWLexer.gi:25:5:25:17:451:463: Warning: The exported terminal symbol begin_example was not generated by any rule in this grammar
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationKWLexer.gi:26:5:26:15:470:480: Warning: The exported terminal symbol end_example was not generated by any rule in this grammar
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:38:5:38:16:853:864: Informative: The terminal CtlCharNotWS is useless.
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:51:5:51:14:1231:1240: Informative: The terminal AfterASCII is useless.
/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi:34:9:34:11:824:826: Error: The nonterminal any is useless.



/home/jurgenv/imp/org.eclipse.imp.formatting/src/org/eclipse/imp/formatting/parser/FormattingSpecificationLexer.gi is LALR(1).


Number of Terminals: 102
Number of Nonterminals: 41
Number of Productions: 176
Number of Items: 371
Number of States: 20
Number of Shift actions: 7
Number of Goto actions: 13
Number of Shift/Reduce actions: 359
Number of Goto/Reduce actions: 102
Number of Reduce actions: 20
Number of Shift-Reduce conflicts: 0
Number of Reduce-Reduce conflicts: 0

Number of entries in base Action Table: 135
Additional space required for compaction of Action Table: 14.0%

Number of unique terminal states: 18
Number of Shift actions saved by merging: 20
Number of Conflict points saved by merging: 0
Number of Reduce actions saved by merging: 0
Number of Reduce saved by default: 19

Number of entries in Terminal Action Table: 365
Additional space required for compaction of Terminal Table: 11.5%

Actions in Compressed Tables:
     Number of Shifts: 7
     Number of Shift/Reduces: 339
     Number of Gotos: 13
     Number of Goto/Reduces: 102
     Number of Reduces: 1
     Number of Defaults: 13

Parsing Tables storage:
    Storage required for BASE_CHECK: 176 Bytes
    Storage required for BASE_ACTION: 662 Bytes
    Storage required for TERM_CHECK: 472 Bytes
    Storage required for TERM_ACTION: 816 Bytes
